### ISSUE TITLE
Double Daily Almanac Email and Days Being Entered Twice Into Spreadsheet

### ISSUE THREAD

**Issue by DillyTaunt** [jamietr1/google-docs-writing-tracker#25]
I get the "Daily Writing" email once but am receiving two identical "Daily Almanac" emails. I usually just ignore this because I don't understand what's really going on but then I started noticing that some days I get a negative word count. I read your replies in one of the issues reported about how if I'm accidentally editing in my Snapshot/Earlier folder then this could result in a negative word count and I'm pretty sure I'm not doing that. 

I can't figure out what's going on but also everything seems to have doubled. I haven't kept an independent account of my writing stats to verify, but I've been running your scripts for 14 days now and the number of days it says I've written out of the last X days is off. I've only been running the scripts for 2 weeks but it says I've been writing 13 out of the last 27 days! And I know I've missed a day or two here of writing (those days my Word count emails will correctly state I've written zero words) but the Daily Almanacs are off, the next day I write the Daily Almanac will update by +2. Going from 11 out of 25 days to 13 out of 27 days for example. I took a look at my Google Writing Tracker Data spreadsheet and in the writing tab I see that each day shows up twice. On days I wrote there's an accurate row for the day with the word count and another duplicate row only with a word count of zero. For the last few days of this writing there will be one row with the accurate word count and an accompanying row for the same date with a negative word count- maybe this is somehow to do with the Snapshot/Earlier version of the file being edited or something. 

Can I simply delete the duplicate rows with the incorrect word counts to fix my stats? How to remedy the issue of the day being entered in twice into the spread sheet and prevent a double email being sent?

Thank you.

**Comment by DillyTaunt** [comment]
Happy New Year!

Hello Mr Rubin, I just wanted to drop a line and let you know that your
trouble shooting advice worked- I had entered the instructions for setting
the triggers twice!

Cheers!
Phong

On Sun, Nov 23, 2014 at 10:05 PM, Jamie Todd Rubin <notifications@github.com

**Comment by jamietr1** [comment]
Thanks for letting me know! Happy New Year!
