### ISSUE TITLE
Method Session.getTimeZone is deprecated.

### ISSUE THREAD

**Issue by lsolesen** [jamietr1/google-docs-writing-tracker#29]
I am getting this

    Method Session.getTimeZone is deprecated.
    File: Code Line: 12

When editing the script.

**Comment by katychuang** [comment]
Replacing  `var TIME_ZONE = Session.getTimeZone();` with 
`var TIME_ZONE = Session.getScriptTimeZone();` worked for me.

**Comment by lsolesen** [comment]
Seems that this has been fixed in the newest version.
